---
- name: "sre quest hosts"
  hosts:
    - vm2.sth33.srequest.ru
    - vm3.sth33.srequest.ru
  vars_files:
    - vars/proxy.yml
    - vars/zabbix.yml
    - vars/nginx.yml
    - vars/wordpress.yml
    - vars/mysql_exporter.yml
    - vars/node_exporter.yml
  environment:
    http_proxy: "{{ proxy_address }}"
  become: true
  roles:
    - {role: 'tools/prepare', tags: prepare}
    - {role: 'tools/proxy', tags: proxy}
    - {role: 'web/nginx', tags: nginx}
    - {role: 'tools/firewall', tags: firewall}   #After Nginx because UFW need Nginx profile installed
    - {role: 'web/php', tags: php}
    - {role: 'database/mysql', tags: mysql}
    - {role: 'web/wordpress', tags: wordpress}
    - {role: 'monitoring/node_exporter', tags: node_exporter}
    - {role: 'monitoring/mysqld_exporter', tags: mysqld_exporter}
    - {role: 'monitoring/zabbix_agent', tags: zabbix_agent}
