---
- name: Add epel repo
  dnf:
    name: epel-release
    state: present

- name: Update system
  dnf:
    name: "*"
    state: latest
  
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Install useful utilities
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - htop
      - iotop
      - iftop
      - mc
      - vim
      - systemd-timesyncd