---
- name: Update system
  apt:
    name: "*"
    state: latest

- name: Install useful utilities
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - htop
      - iotop
      - iftop
      - mc
      - vim
      - systemd-timesyncd