---
- include_tasks: install-AlmaLinux.yml
  when: ansible_os_family == 'AlmaLinux'

- include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Add public key
  authorized_key:
    user: "{{ansible_user}}"
    state: present
    manage_dir: yes
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Disable password authentication
  lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^(.*)PasswordAuthentication(.*)$'
    line: 'PasswordAuthentication no'
  notify:
      - restart sshd

- name: Set timezone
  command: 'timedatectl set-timezone "Europe/Moscow"'

- name: Enable NTP
  command: 'timedatectl set-ntp true'