---
# See available releases: https://github.com/prometheus/node_exporter/releases/
node_exporter_version: '1.3.1'
node_exporter_arch: 'amd64'
node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz

node_exporter_bin_path: /usr/local/bin/node_exporter

node_exporter_options: '--collector.systemd --collector.systemd.unit-include="(nginx|bird|php-fpm|mariadb)\\.service"'

node_exporter_web_config: /etc/prometheus/node_exporter/web.yml

node_exporter_state: started
node_exporter_enabled: true
