---
- name: install nginx
  apt:
    name: nginx
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: remove default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  ignore_errors: "{{ ansible_check_mode }}"

- name: set nginx config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/conf.d/sre-{{ hostvars[inventory_hostname].inventory_hostname }}-wp.conf"
  notify:
   - restart nginx

- name: create conf.d.enabled directory
  file:
    state: directory
    dest: /etc/nginx/conf.d.enabled/

- name: create nginx link
  ignore_errors: "{{ ansible_check_mode }}"
  file:
    state: link
    src: "/etc/nginx/conf.d/sre-{{ hostvars[inventory_hostname].inventory_hostname }}-wp.conf"
    dest: "/etc/nginx/conf.d.enabled/sre-{{ hostvars[inventory_hostname].inventory_hostname }}-wp.conf"
  notify:
   - restart nginx

- name: check if nginx is started and enabled on boot
  systemd:
    daemon_reload: yes
    name: nginx
    enabled: yes
    state: started
  ignore_errors: "{{ ansible_check_mode }}"
