---
- name: install mariadb
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-mysqldb
      - mariadb-common
      - mariadb-server

#- name: set mysql config my.cnf
#  template:
#    src: my.cnf.j2
#    dest: /etc/mysql/my.cnf
#    owner: root
#    group: root
#    mode: 0644
#  notify: restart mysql

#- name: create mysql include directory
#  file:
#    path: /etc/mysql/conf.d
#    state: directory
#    owner: root
#    group: root
#    mode: 0755

#- name: create datadir
#  file:
#    path: /var/lib/mysql
#    state: directory
#    owner: mysql
#    group: mysql
#    mode: 0755
#    setype: mysqld_db_t

- name: Ensure MySQL is started and enabled on boot.
  service: "name=mariadb state=started enabled=true"
  ignore_errors: "{{ ansible_check_mode }}"
